# Generated by Django 5.1.6 on 2025-02-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
